<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.Abstractions" Version="2.3.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.22">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BlueHome.Server.Application\BlueHome.Server.Application.csproj" />
		<ProjectReference Include="..\BlueHome.Server.Infrastructure\BlueHome.Server.Infrastructure.csproj" />
	</ItemGroup>
</Project>